spring:
  application:
    name: studysync-backend

  # Profile-specific configs loaded on top of this
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # JPA common settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

# Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method